set nu
syntax on
 
filetype indent plugin on
set wildmenu
 
set modeline
set background=dark
 
set tabstop=8 expandtab shiftwidth=4 softtabstop=4

map <C-E> :tabe
map <C-P> :tabp
map <C-N> :tabn

nnoremap <CR> G
nnoremap <BS> gg

" vp doesn't replace paste buffer
function! RestoreRegister()
  let @" = s:restore_reg
  return ''
endfunction
function! s:Repl()
  let s:restore_reg = @"
  return "p@=RestoreRegister()\<cr>"
endfunction
vmap <silent> <expr> p <sid>Repl()
